-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 22:10:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
DROP DATABASE IF EXISTS laravel;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel` DEFAULT CHARACTER SET utf8 ;
USE `laravel` ;

-- -----------------------------------------------------
-- Table `laravel`.`user`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `laravel`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(300) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `url` VARCHAR(150) NULL,
  `emailVerificateAt` DATE NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updateAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `emailUnique` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL default 8,
  `firstName` VARCHAR(100) NOT NULL,
  `secondName` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address1` VARCHAR(100) NOT NULL,
  `address2` VARCHAR(100) NULL,
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_cliente_idusuario_idx` (`idUser` ASC),
  CONSTRAINT `fk_customer_idusuario`
    FOREIGN KEY (`idUser`)
    REFERENCES `laravel`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`proveedor` (
  `idProveedor` INT NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(45) NOT NULL,
  `contactFName` VARCHAR(45) NOT NULL,
  `contactLName` VARCHAR(45) NOT NULL,
  `contactTitle` VARCHAR(45) NOT NULL,
  `address1` VARCHAR(100) NOT NULL,
  `address2` VARCHAR(100) NULL,
  `city` VARCHAR(100) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `fax` VARCHAR(255) NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updateAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`promotion` (
  `idPromotion` INT NOT NULL AUTO_INCREMENT,
  `discount` DECIMAL (3,3) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `promotionCode` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updateAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idPromotion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `idSupplier` INT NOT NULL default 3,
  `idPromotion` INT NOT NULL default 4,
  `productName` VARCHAR(45) NOT NULL,
  `productDescription` VARCHAR(45) NULL,
  `price` DECIMAL(7,3) NOT NULL,
  `type` VARCHAR(45) NULL,
  `size` INT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updateAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_product_idSupplier_idx` (`idSupplier` ASC),
  INDEX `fk_product_idPromotion_idx` (`idPromotion` ASC),
  CONSTRAINT `fk_product_idSupplier`
    FOREIGN KEY (`idSupplier`)
    REFERENCES `laravel`.`supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_idPromotion`
    FOREIGN KEY (`idPromotion`)
    REFERENCES `laravel`.`promotion` (`idPromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`orders` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL default 7,
  `numOrder` VARCHAR(45) NOT NULL,
  `successful` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_order_idUser_idx` (`idUser` ASC),
  CONSTRAINT `fk_order_idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `laravel`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`orderdetails` (
  `idOrderdetails` INT NOT NULL AUTO_INCREMENT,
  `idOrder` INT NOT NULL default 5,
  `idProduct` INT NOT NULL default 6,
  `numOrder` INT(5) NOT NULL,
  `cuantity` INT NOT NULL DEFAULT 1,
  `updateAt` TIMESTAMP NOT NULL,
  INDEX `fk_basket_idProduct_idx` (`idProduct` ASC),
  INDEX `fk_basket_order_idx` (`idOrder` ASC),
  PRIMARY KEY (`idOrderdetails`),
  CONSTRAINT `fk_orderdetails_idProduct`
    FOREIGN KEY (`idProduct`)
    REFERENCES `laravel`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetails_idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `laravel`.`orders` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`token` (
  `idToken` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL DEFAULT 1,
  `token` VARCHAR(300) NOT NULL,
  `hmac` VARCHAR(300) NULL,
  `ip` VARCHAR(45) NULL,
  `platform` VARCHAR(45) NULL,
  `active` TINYINT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idToken`),
  INDEX `fk_token_idUser_idx` (`idUser` ASC),
  CONSTRAINT `fk_token_idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `laravel`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idAdmin`),
  INDEX `fk_admin_idUser_idx` (`idUser` ASC),
  CONSTRAINT `fk_admin_idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `laravel`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`photo` (
  `idPhoto` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5) NOT NULL,
  `stock` INT(255) NOT NULL,
  PRIMARY KEY (`idPhoto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`customerHasPhoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`customerHasPhoto` (
  `customerIdCustomer` INT NOT NULL,
  `photoIdPhoto` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  INDEX `fk_customerHasPhoto_photo1_idx` (`photoIdPhoto` ASC),
  INDEX `fk_customerHasPhoto_customer1_idx` (`customerIdCustomer` ASC),
  CONSTRAINT `fk_customerHasPhoto_customer1`
    FOREIGN KEY (`customerIdCustomer`)
    REFERENCES `laravel`.`customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customerHasPhoto_photo1`
    FOREIGN KEY (`photoIdPhoto`)
    REFERENCES `laravel`.`photo` (`idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`payment` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `cardNumber` BIGINT(250) NOT NULL,
  `expiryDATE` TIMESTAMP NOT NULL,
  `ownerName` VARCHAR(255) NOT NULL,
  `cvv` VARCHAR(10) NOT NULL,
  `updateAt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idCustomer`),
  CONSTRAINT `fk_payment_idCustomer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `laravel`.`customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`productHasPromotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`productHasPromotion` (
  `productIdProduct` INT NOT NULL auto_increment,
  `promotionIdPromotion` INT NOT NULL default 2,
  `createdAt` TIMESTAMP NOT NULL,
  `updateAt` TIMESTAMP NOT NULL,
  INDEX `fk_productHasPromotion_promotion1_idx` (`promotionIdPromotion` ASC),
  INDEX `fk_productHasPromotion_product1_idx` (`productIdProduct` ASC),
  CONSTRAINT `fk_productHasPromotion_product1`
    FOREIGN KEY (`productIdProduct`)
    REFERENCES `laravel`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productHasPromotion_promotion1`
    FOREIGN KEY (`promotionIdPromotion`)
    REFERENCES `laravel`.`promotion` (`idPromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`category` (
  `idCategory` INT NOT NULL auto_increment,
  `name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`photo_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`photo_has_category` (
  `photoIdPhoto` INT NOT NULL,
  `categoryIdCategory` INT NOT NULL,
  INDEX `fk_photo_has_category_category1_idx` (`categoryIdCategory` ASC),
  INDEX `fk_photo_has_category_photo1_idx` (`photoIdPhoto` ASC),
  CONSTRAINT `fk_photo_has_category_photo1`
    FOREIGN KEY (`photoIdPhoto`)
    REFERENCES `laravel`.`photo` (`idPhoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photo_has_category_category1`
    FOREIGN KEY (`categoryIdCategory`)
    REFERENCES `laravel`.`category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel`.`product_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel`.`product_has_category` (
  `productIdProduct` INT NOT NULL,
  `categoryIdCategory` INT NOT NULL,
  INDEX `fk_product_has_category_category1_idx` (`categoryIdCategory` ASC),
  INDEX `fk_product_has_category_product1_idx` (`productIdProduct` ASC),
  CONSTRAINT `fk_product_has_category_product1`
    FOREIGN KEY (`productIdProduct`)
    REFERENCES `laravel`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_category_category1`
    FOREIGN KEY (`categoryIdCategory`)
    REFERENCES `laravel`.`category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('lainsby0', '2f06ce8eaf4114ddce1879be47c6bc7e', 'ekorbmaker0@desdev.cn', '2021/03/03 22:12:34', '2021/03/03 22:12:34 ', '2021/03/03', 'http://dummyimage.com/119x100.png/5fa2dd/ffffff');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('mhousecroft1', '4b70c95c94b5e34f349e6c2b705b70eb', 'mattrill1@elpais.com', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03 ', 'http://dummyimage.com/173x100.png/dddddd/000000');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('nbunston2', '4be462926514f02a7a71fbd3cca43b9c', 'tvarley2@parallels.com', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03 ', 'http://dummyimage.com/144x100.png/ff4444/ffffff');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('athouless3', '416a82bbad217f99ee89253c1aebe7ce', 'mkubacek3@hibu.com', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03', 'http://dummyimage.com/225x100.png/5fa2dd/ffffff');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('jchater4', '4f425eb80ace1d81ef986c3ad3a18841', 'yjanas4@sakura.ne.jp', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03', 'http://dummyimage.com/184x100.png/dddddd/000000');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('mclemson5', '64b323976e956fccffa8c9460ea22de2', 'gsturrock5@bizjournals.com', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03', 'http://dummyimage.com/189x100.png/cc0000/ffffff');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('iiwaszkiewicz6', '25e38b700093f90f3fc9d62007d7178d', 'tilsley6@purevolume.com', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03', 'http://dummyimage.com/193x100.png/5fa2dd/ffffff');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('twitherbed7', '4662c2fd71eaa92fad742ffe2cc10d73', 'fantunez7@theguardian.com', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03', 'http://dummyimage.com/118x100.png/dddddd/000000');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('psalkeld8', '8f96df14cf1b3b012a9dceec95f0dc1c', 'lbreffit8@ted.com', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03', 'http://dummyimage.com/201x100.png/ff4444/ffffff');
insert into user (userName, hash, email, createdAt, updateAt, emailVerificateAt, url) values ('mkobieriecki9', 'b361ccc43443934534a7c808615ec97e', 'nerrichelli9@intel.com', '2021/03/03 22:12:34', '2021/03/03 22:12:34', '2021/03/03', 'http://dummyimage.com/122x100.png/ff4444/ffffff');


insert into token (token, hmac, ip, platform, active, createdAt) values ('http://thetimes.co.uk/lacus/morbi/sem/mauris/laoreet/ut/rhoncus.jsp', '75-1B-9F-B9-A4-21', '42.65.233.71', 'Y-find', 85, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('https://tumblr.com/magna/bibendum/imperdiet.js', 'D6-1A-50-64-77-5F', '0.202.106.49', 'Viva', 16, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('https://elpais.com/erat.xml', 'B9-C8-9C-15-B0-7B', '109.158.236.85', 'Mat Lam Tam', 33, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('http://themeforest.net/quisque.html', 'B3-B0-B2-8A-DE-96', '106.42.237.252', 'Tampflex', 31, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('https://ucla.edu/interdum/in/ante/vestibulum/ante/ipsum.jsp', 'CA-51-5D-A9-6A-B3', '8.142.71.99', 'Zamit', 89, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('https://dailymail.co.uk/quis/turpis/sed/ante/vivamus/tortor.aspx', 'C3-B4-91-C9-45-21', '125.85.204.251', 'Fix San', 79, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('https://alexa.com/eget/nunc/donec/quis.jsp', '83-80-C2-EF-87-C0', '144.94.7.155', 'Zathin', 57, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('https://bigcartel.com/luctus/cum/sociis/natoque/penatibus.jpg', '0E-56-2E-FF-B7-E5', '7.93.21.171', 'Opela', 84, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('https://bigcartel.com/varius/ut.png', '11-E3-9A-73-24-26', '64.234.230.126', 'Voyatouch', 76, '2021/03/03');
insert into token (token, hmac, ip, platform, active, createdAt) values ('http://admin.ch/turpis.png', '61-44-91-44-22-0A', '35.42.118.129', 'Tampflex', 77, '2021/03/03');


insert into orders (numOrder, successful, createdAt) values ('08b02845664b506ea10b41e77bc95c1d08c8e742', 309, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('577eff2be86b002231dac12d06ec2c0953f2ce25', 603, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('d0199391ac9e1d6ee1e0bcbdabd55cb9356322f5', 215, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('c2d34b2785d921397ec344c484ab2f1379e03c0a', 713, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('73ce57e4af75592f4064013ecebbf007e1a2052b', 190, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('37c8fbbd51be970b7cc8340e0387d9187cd4ea7b', 224, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('2fb0fcf506ee858dc010dcc9e61a5605bff54f70', 576, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('56ac0fbcefa2f8da34e462cdcda6e98add993d25', 938, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('13d5c2d5bf97474ec138aeff24b238c3ef4d2f66', 544, '2021/03/03 22:12:34');
insert into orders (numOrder, successful, createdAt) values ('21789fe478512e74879b63711bc898cb2bc9a1cd', 734, '2021/03/03 22:12:34');


insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Skyvu', 'Jacquenette', 'Drinkall', 'Dr', '677 Veith Alley', '4907 Commercial Center', 'Chaem Luang', '44110', 'Thailand', '515-548-1186', 'jdrinkall0@feedburner.com', '503-499-8277', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Vinder', 'Trumann', 'Leteurtre', 'Dr', '6667 Sugar Avenue', null, 'Rybnik', '44-274', 'Poland', '258-478-6684', 'tleteurtre1@mapquest.com', '158-546-7037', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Zoomdog', 'Bancroft', 'Rennebach', 'Mrs', '9 Susan Junction', '82839 Arrowood Hill', 'Pinillos', '134008', 'Colombia', '656-534-3834', 'brennebach2@naver.com', '515-909-5577', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Yakitri', 'Jocelin', 'Aucock', 'Mrs', '80174 Roxbury Crossing', null, 'San Andros', '44110', 'Bahamas', '417-780-6029', 'jaucock3@shinystat.com', '526-509-2424', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Bluejam', 'Anitra', 'Wisniewski', 'Rev', '60 Bashford Hill', null, 'Kribi', '44110', 'Cameroon', '502-748-2348', 'awisniewski4@uol.com.br', '680-646-6169', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Abatz', 'Merrick', 'Di Angelo', 'Rev', '03611 Lien Hill', '79 Manley Court', 'Dallas', '75260', 'United States', '214-509-5012', 'mdiangelo5@wired.com', '574-636-0667', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Mynte', 'Vally', 'Oliva', 'Dr', '6 Mallard Center', '4 Green Hill', 'Vetluzhskiy', '157510', 'Russia', '893-315-0932', 'voliva6@naver.com', '197-225-4427', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Demivee', 'Angel', 'Liger', 'Rev', '38147 Sugar Place', '8 Norway Maple Court', 'Upernavik', '3962', 'Greenland', '430-399-3604', 'aliger7@berkeley.edu', '213-715-1928', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Skyndu', 'Erwin', 'Goodwins', 'Mr', '5 Loeprich Hill', null, 'Yongtai','44110', 'China', '191-234-5555', 'egoodwins8@toplist.cz', '211-567-4796', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into supplier (companyName, contactFName, contactLName, contactTitle, address1, address2, city, postalCode, country, phone, email, fax, createdAt, updateAt) values ('Feedfire', 'Sophia', 'Espino', 'Mrs', '5 Annamark Parkway', null, 'Ko Samui', '84140', 'Thailand', '445-288-7407', 'sespino9@google.com.hk', '980-267-8811',  '2021/03/03 22:12:34', '2021/03/03 22:12:34');


insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.02, '9394793e5d9db61b8e8eb0b669d07e6ef0419633', '927ae017d60e4939877d03eb9adabab6b52a8c90', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.25, '42e3b402712644de4fb62c32072d4fd3fda936dc', '7a159c0fb9fac86f1f25319467bdbf8a377190ec', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.73, 'eaa21518f8dca236e9aee9d4cd07db823006a7c3', '39a812a21e509c38fecc8e4390446dbea9acd2e8', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.88, '02452b571070b669e84bd74db883f80be20b4b72', '7bd6a3e29376f3127bde40b50484af78268ff44b', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.67, '18d7a8f57ee997f829ede54bcb223fe0935d76df', '8d0c6ffb2812d39d6ba9d9f8ec559464af01030c', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.04, 'fd79bd1569febf7a521840ff8100d48258fab2bc', '7af2a90dda77d1db0d2aa83b601fc376e195ec9c', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.36, 'd502f2e4cbf219b79c2551be8fda62433fe0e4cc', '8d482939e1797cbdbce11d647a946f81c3e477c1', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.13, '0950735b0325c99484e7b60fbe3f5963e2322607', '54377ff23309e11898c697eef47b0eb6b844bd45', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.15, '0789eb2f80b26fe12962720e27979197eab444e0', '2ffcd8ca62a0c65c6956a60d1ade4afdb798b8a8', '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into promotion (discount, code, promotionCode, createdAt, updateAt) values (0.28, '41327a104638fbc02758c0c3ec5d741aef2ea821', '45511f1f93a624099a1f9512dde2c7503220cabb', '2021/03/03 22:12:34', '2021/03/03 22:12:34');



insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Beer - Fruli', 'Adaptive encompassing strategy', '120.07', 'application/mspowerpoint', 3, '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Easy Off Oven Cleaner', 'Ergonomic regional knowledge base', '381.01', 'application/vnd.ms-excel', 24, '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Beer - Sleeman Fine Porter', 'Grass-roots holistic benchmark', '586.98', 'application/x-excel', 47, '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Sherry - Dry', 'Synchronised analyzing emulation', '34.79', 'application/pdf', 68, '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Shrimp, Dried, Small / Lb', 'Business-focused intangible definition', '887.65', 'application/vnd.ms-powerpoint', 77, '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Fish - Base, Bouillion', 'Vision-oriented asynchronous application', '7.38', 'application/msword', 80, '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Bread Base - Toscano', 'Distributed bottom-line moratorium', '25.38', 'text/plain', 94, '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Muffin Mix - Corn Harvest', 'Switchable foreground firmware', '395.70', 'application/x-msexcel', 13, '2021/03/03 22:12:34','2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Wine - Rioja Campo Viejo', 'Front-line reciprocal internet solution', '244.99', 'image/png', 4, '2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into product (productName, productDescription, price, type, size, createdAt, updateAt) values ('Cabbage - Green', 'Streamlined multi-tasking matrix', '210.05', 'image/png', 23, '2021/03/03 22:12:34', '2021/03/03 22:12:34');


insert into orderdetails (numOrder, cuantity, updateAt) values (683, 867, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (38, 216, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (501, 823, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (903, 732, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (295, 514, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (753, 881, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (653, 245, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (165, 366, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (317, 810, '2021/03/03 22:12:34');
insert into orderdetails (numOrder, cuantity, updateAt) values (796, 627, '2021/03/03 22:12:34');


insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');
insert into productHasPromotion (createdAt, updateAt) values ('2021/03/03 22:12:34', '2021/03/03 22:12:34');


insert into photo (url, name, price, stock) values ('http://yellowpages.com/pellentesque/quisque/porta.json', 'Beastmaster, The', 17, '200');
insert into photo (url, name, price, stock) values ('https://vinaora.com/ut/at/dolor/quis.json', 'Storm in Summer, A', 77, '200');
insert into photo (url, name, price, stock) values ('http://spotify.com/lorem/ipsum.jsp', 'Indie Game: The Movie', 70, '200');
insert into photo (url, name, price, stock) values ('https://wiley.com/justo/lacinia/eget/tincidunt/eget/tempus.json', 'Upside Down', 67, '200');
insert into photo (url, name, price, stock) values ('http://smh.com.au/tincidunt/eget/tempus/vel/pede/morbi.aspx', '3096 Days', 21, '200');
insert into photo (url, name, price, stock) values ('https://1688.com/odio/donec/vitae.xml', 'Lies and Illusions', 60, '200');
insert into photo (url, name, price, stock) values ('https://engadget.com/dui/vel/nisl.json', 'Incredible Hulk Returns, The', 41, '200');
insert into photo (url, name, price, stock) values ('http://craigslist.org/nulla/elit/ac/nulla/sed.jpg', 'Italian Straw Hat', 48, '200');
insert into photo (url, name, price, stock) values ('http://intel.com/duis/faucibus.js', '9', 35, '200');
insert into photo (url, name, price, stock) values ('https://histats.com/donec/semper/sapien/a/libero.json', 'Man You Had in Mind', 19, '200');


insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Hardy', 'Querree', '9775922206', 'Genderfluid', 'hquerree0@woothemes.com', 'hquerree0@cbslocal.com');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Hubie', 'Brownsea', '6283848731', 'Genderfluid', 'hbrownsea1@scientificamerican.com', 'hbrownsea1@google.ru');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Aile', 'Reuter', '6831002323', 'Genderqueer', 'areuter2@comcast.net', 'areuter2@google.cn');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Marylin', 'Lesper', '6993874898', 'Non-binary', 'mlesper3@wsj.com', 'mlesper3@parallels.com');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Brigg', 'Karpe', '4025597157', 'Polygender', 'bkarpe4@berkeley.edu', 'bkarpe4@umich.edu');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Denys', 'Chittock', '3125189930', 'Agender', 'dchittock5@cnbc.com', 'dchittock5@aol.com');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Arlena', 'Verbrugge', '7948147877', 'Agender', 'averbrugge6@npr.org', 'averbrugge6@sfgate.com');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Vaughan', 'Rame', '9529731160', 'Female', 'vrame7@biblegateway.com', 'vrame7@tripadvisor.com');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Josiah', 'Jaouen', '6901481649', 'Genderqueer', 'jjaouen8@woothemes.com', 'jjaouen8@constantcontact.com');
insert into customer (firstName, secondName, phone, gender, address1, address2) values ('Leone', 'Bertwistle', '8644608536', 'Male', 'lbertwistle9@goo.ne.jp', 'lbertwistle9@wisc.edu');

insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('3542319037308221', '2021/03/03 22:12:34', 'Raoul Verne', 506, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('5602258570182577', '2021/03/03 22:12:34', 'Denys Frandsen', 766, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('3582704014453671', '2021/03/03 22:12:34', 'Carlota Decroix', 277, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('4405589923749993', '2021/03/03 22:12:34', 'Bat Crole', 977, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('5602238564004516', '2021/03/03 22:12:34', 'Hatti Lagde', 790, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('3534307440436135', '2021/03/03 22:12:34', 'Torin Maskelyne', 843, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('201754092694370', '2021/03/03 22:12:34', 'Ernesta Willshee', 971, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('3583569328046043', '2021/03/03 22:12:34', 'Maxy Wilman', 385, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('30482136957309', '2021/03/03 22:12:34', 'Gabriel Naile', 409, '2021/03/03 22:12:34');
insert into payment (cardNumber, expiryDATE, ownerName, cvv, updateAt) values ('201562132789138', '2021/03/03 22:12:34', 'Darby Eleshenar', 350, '2021/03/03 22:12:34');

insert into category (name) values ('dgenner0');
insert into category (name) values ('sflahive1');
insert into category (name) values ('cgerard2');
insert into category (name) values ('clucia3');
insert into category (name) values ('rtaffe4');
insert into category (name) values ('asouttar5');
insert into category (name) values ('ncolwell6');
insert into category (name) values ('jproschke7');
insert into category (name) values ('lgainfort8');
insert into category (name) values ('tsimons9');